/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NewsRouteImport } from './routes/news'
import { Route as AdminPageLoginRouteImport } from './routes/admin-page-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPageLoginRoute = AdminPageLoginRouteImport.update({
  id: '/admin-page-login',
  path: '/admin-page-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-page-login': typeof AdminPageLoginRoute
  '/news': typeof NewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-page-login': typeof AdminPageLoginRoute
  '/news': typeof NewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/guides': typeof GuidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-page-login': typeof AdminPageLoginRoute
  '/news': typeof NewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-page-login'
    | '/news'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/guides/$slug'
    | '/admin/'
    | '/blog/'
    | '/guides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-page-login'
    | '/news'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/guides/$slug'
    | '/admin'
    | '/blog'
    | '/guides'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-page-login'
    | '/news'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/guides/$slug'
    | '/admin/'
    | '/blog/'
    | '/guides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminPageLoginRoute: typeof AdminPageLoginRoute
  NewsRoute: typeof NewsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-page-login': {
      id: '/admin-page-login'
      path: '/admin-page-login'
      fullPath: '/admin-page-login'
      preLoaderRoute: typeof AdminPageLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminPageLoginRoute: AdminPageLoginRoute,
  NewsRoute: NewsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
